"""Interactive, secret-free first-run setup for Agent Notifier."""

from __future__ import annotations

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib
import re
from pathlib import Path

from .config import Paths


BEGIN = "# BEGIN agent-notifier setup"
END = "# END agent-notifier setup"


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def _cc_projects(path: Path) -> list[str]:
    if not path.exists():
        return []
    with path.open("rb") as stream:
        data = tomllib.load(stream)
    projects = data.get("projects", [])
    if not isinstance(projects, list):
        return []
    result = []
    for project in projects:
        if isinstance(project, dict):
            name = project.get("name") or project.get("project")
            if name:
                result.append(str(name))
    return result


def _render_routes(
    project: str,
    interactive_chat: str,
    notification_chat: str,
) -> str:
    return "\n".join(
        [
            BEGIN,
            "# Generated by `agent-notifier setup`; no credentials are stored here.",
            "[chat_routes]",
            f'{interactive_chat} = "opencode"',
            f'{notification_chat} = "silent"',
            "",
            "[notification_routes.default]",
            f'project = "{project}"',
            'receive_id_type = "chat_id"',
            f'receive_id = "{notification_chat}"',
            'message_format = "markdown"',
            f'session_key = "feishu:{notification_chat}:terminal"',
            "",
            "[notification_routes.acp]",
            f'project = "{project}"',
            'receive_id_type = "chat_id"',
            f'receive_id = "{interactive_chat}"',
            'message_format = "markdown"',
            f'session_key = "feishu:{interactive_chat}:terminal"',
            END,
            "",
        ]
    )


def configure_routes(
    paths: Paths,
    project: str,
    interactive_chat: str,
    notification_chat: str,
) -> None:
    if interactive_chat == notification_chat:
        raise ValueError("interactive and notification chat IDs must differ")
    paths.ensure_directories()
    source = paths.config_file.read_text(encoding="utf-8") if paths.config_file.exists() else ""
    if BEGIN in source:
        start = source.index(BEGIN)
        end = source.index(END, start) + len(END)
        source = source[:start].rstrip() + "\n\n" + source[end:].lstrip()
    elif re.search(r"(?m)^\s*\[chat_routes\]\s*$", source) or re.search(
        r"(?m)^\s*\[notification_routes\.default\]\s*$", source
    ):
        raise ValueError(
            "config already contains route tables; edit it manually or remove the old route tables first"
        )
    paths.config_file.write_text(
        source.rstrip() + "\n\n" + _render_routes(project, interactive_chat, notification_chat),
        encoding="utf-8",
    )


def run_setup(paths: Paths, project: str | None = None, interactive_chat: str | None = None,
              notification_chat: str | None = None, non_interactive: bool = False) -> None:
    cc_config = Path.home() / ".cc-connect/config.toml"
    if not cc_config.exists():
        raise RuntimeError(
            f"cc-connect config not found: {cc_config}; configure cc-connect first"
        )
    projects = _cc_projects(cc_config)
    project = project or (projects[0] if len(projects) == 1 else None)
    interactive_chat = interactive_chat or None
    notification_chat = notification_chat or None
    if not non_interactive:
        if project is None:
            project = _ask("cc-connect project", projects[0] if projects else "")
        interactive_chat = interactive_chat or _ask("interactive chat_id (Group A)")
        notification_chat = notification_chat or _ask("notification chat_id (Group B)")
    if not project or not interactive_chat or not notification_chat:
        raise ValueError(
            "setup requires project, interactive chat_id, and notification chat_id"
        )
    if projects and project not in projects:
        raise ValueError(f"cc-connect project not found: {project}")
    configure_routes(paths, project, interactive_chat, notification_chat)
    print(f"configured routes: {paths.config_file}")
    print(f"interactive chat: {interactive_chat}")
    print(f"notification chat: {notification_chat}")
    print("credentials remain managed by cc-connect")
